config/routes.rb
Rails.application.routes.draw do

  get 'welcomes/index'

  get 'profiles/index'

  get 'profile/index'

 devise_for :user

 devise_for :restuarant

root to:"restuarants#show"

resources :restuarants do
  collection do
  end  
  member do 
      get 'staff'
      get 'add_drinking'
      get 'add_dessert'
      get 'add_dish'
      post 'add_staff'
      get 'show_staff'
      delete 'destroy_staff'
      get 'report'
    end
end

resources :billings   do
  member do
    get 'index_show'
    get 'report'
  end  
end

resources :registers

resources :waiters

resources :drinkings do
  member do
    patch 'update_drinking' 
  end
  collection do
    get  'drink_search'
  end
end

resources :desserts do
  member do
    patch 'update_dessert'
  end
  collection do
    get  'dessert_search'
  end
end

resources :dishs do
 member do
patch 'update_dish'
  end
  collection do
    get  'dish_search'
  end
end

resources :promotions do
  member do
  patch 'update_promotion'
  end
end

resources :bookings do
  member do
    patch 'update_booking'
  end
end

resource :users, only: [:edit, :update, :new]
  
 resources :tables
 resources :menu_lists do
  collection do
    get 'drinking'
    get 'dessert'
    get 'show'
   end
  member do
    patch 'create_menu'
    get 'payment'
    get 'service_bill'
    get "clear_table"
    get "cancle"
  end
end
  
 resources :showusers do 
 collection do
        get 'showusers'
    end
  end

  resources :profiles do 
 collection do
        get 'profiles'
    end
  end

   resources :orders do 
 collection do
        get 'orders'
    end
  end

  resources :kitchens do
    collection do
      get 'dish_kitchen'
      get 'drinking_kitchen'
      get 'dessert_kitchen'
    end
  end

end

app/models/dish.rb
class Dish
  include Mongoid::Document
  belongs_to :restuarant

   field :dish_name,    type: String
   field :dish_price,   type: Float
   validates :dish_name,                  presence: {message: "กรุณาระบุชื่อเมนู"},uniqueness: {message: "ชื่อเมนูนี้มีอยู่ในระบบแล้ว"}
   validates :dish_price,             presence: {message: "กรุณาระบุราคา"},numericality: {message: "กรุณาระบุราคาเป็นตัวเลข"}

end

app/controllers/dishs_controller.rb
class DishsController < ApplicationController

	def new
		@dish = Dish.new
	end

  def show
    @restuarant_show = Restuarant.where(id: current_user.current_restuarant).first
    @restuarant_user = Restuarant.where(user_id: current_user.id) 
    @restuarant= Restuarant.where(id: current_user.current_restuarant).first
    @dish = Dish.where(restuarant_id: @restuarant.id).order(dish_price: "aesc")
    @dishs = Dish.new
  end

  def edit
    @dish= Dish.find(params[:id])
  end

	def update
    @restuarant= Restuarant.where(id: current_user.current_restuarant).first
    @dish = Dish.new(dish_name: params[:dish_name],dish_price: params[:dish_price],restuarant_id: @restuarant.id)
    if @dish.save
      flash[:notice] = "เพิ่มเมนูเรียบร้อยแล้ว"
      redirect_to  dish_path
    else
      flash[:error] = "กรุณาระบุข้อมูลให้ครบถ้วน"
      redirect_to add_dish_restuarant_path
    end
  end

  def update_dish
      @dish= Dish.find(params[:id])
      @restuarant= Restuarant.where(_id: @dish.restuarant_id)
    if @dish.update(dish_name: params[:dish][:dish_name],dish_price: params[:dish][:dish_price])
      flash[:notice] = "แก้ไขเมนูเรียบร้อยแล้ว"
      redirect_to  dish_path(@restuarant[0].id)
    else
      flash[:error] = "กรุณาระบุข้อมูลให้ครบถ้วน"
       redirect_to dish_path
    end
  end

  def destroy
      @dish= Dish.find(params[:id])
      @restuarant= Restuarant.where(_id: @dish.restuarant_id)
      @dish.destroy
      flash[:notice] = "ลบเมนูเรียบร้อยแล้ว"
      redirect_to dish_path(@restuarant[0].id)
  end

  def dish_search
    @dish_name = params[:dish_name]  
    dish = Dish.where(restuarant_id: current_user.current_restuarant)
      if @dish_name != ""
        @dish = dish.inject([]) do |name,dish|
          if dish.dish_name.include?(@dish_name)
            name << dish
          end 
            name
        end
        render json: @dish
      else
        render json: @dish
      end
  end  

end

app/helpers/dishs_helper.rb
module DishsHelper
end

app/views/dishs/edit.html.erb
<%= form_for(@dish, url: update_dish_dish_url, method: :patch) do |f| %>
<hr>
    <div class="panel panel-primary bigmshoadow" >
      <div class="panel-heading gradient"><h3><i class="fa fa-pencil-square-o" ></i> แก้ไขเมนู</h3>  
      </div>
        <div class="panel-body ">
         <div class="form-horizontal">
      
           <div class="form-group">
            <%= f.label "ชื่อเมนู : ", class: "col-sm-2 control-label"%>
          <div class="col-sm-3">
          <%= f.text_field :dish_name, class: "form-control" %>
        </div>
      </div>

       <div class="form-group">
            <%= f.label "ราคา : ", class: "col-sm-2 control-label"%>
          <div class="col-sm-3">
          <%= f.text_field :dish_price, class: "form-control" %>
        </div>
      </div>

           <div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<%= f.submit "ยืนยัน",class: "btn btn-success" %>
              	</div>
          </div>  
    	</div> 
  	</div>

<% end %>

app/views/dishs/new.html.erb
new.html.erb

app/views/dishs/show.html.erb
<hr>
    <div class="panel panel-primary" >
        <div class="panel-heading gradient">
       		<div class="col-md-6">
			<h3 style=" margin-top: 2%;"><i class="fa fa-cutlery">&nbsp;</i> 
      		อาหารทั้งหมด
        	</h3>
       </div>
             <div class="text-right">
             	<button  type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"><i class="fa fa-search-plus"></i>
                เพิ่มเมนู</button>
            </div>
        </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      </div>
        <div class="panel-body">
			<table class="table table-striped table-hover table-condensed">
			    <thead>
			      <tr class="info">
			        <th>ลำดับ</th>
			        <th>ชื่อ</th>
			        <th>ราคา/บาท</th>
              <th></th> 
              <th></th> 
			      </tr>
			    </thead>

			    <tbody>
			      <% @dish.each_with_index do |f, i| %>
				      <tr>	 		 
			              <td><%= i + 1 %></td>
						        <td><%= f.dish_name %></td>
						        <td><%= f.dish_price %></td>
						        <td class="text-right"><%= link_to edit_dish_path(f), class: 'btn btn-info' do %><i class="fa fa-pencil-square-o" ></i> แก้ไข
                    <%end%> <%= link_to dish_path(f), method: :delete, data: { confirm: 'ยืนยันการลบ' }, 
                class: 'btn btn-danger' do %><i class="fa fa-trash-o" ></i> ลบ
                    <%end%></td>
			          <%end%>
				      </tr>
			  </tbody>
			</table>
  </div>
     	</div>
     	</div>

<%= form_for(@dishs, url: dish_url, method: :patch) do |f| %>

<!-- Modal -->
<form>
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">เพิ่มเมนู</h4>

     </div>
      <div class="modal-body">
  <div class="form-group">
   <label>ชื่อเมนู</label>
    <input type="text" class="form-control" name="dish_name">
 </div>
  <div class="form-group">
  	<div class="input-group">
   	<label>ราคา.-</label>
          <div class="input-group">
            <input type="text" class = "form-control" name= "dish_price">
          <div class="input-group-addon">บาท.-</div>
         </div>
  </div>

     </div>

      <div class="modal-footer">

        <%= f.submit "เพิ่มเมนู",class: "btn btn-success" %>

     </div>

   </div>

  </div>
</div>

</form>
<%end%>