config/routes.rb
Rails.application.routes.draw do

  get 'welcomes/index'

  get 'profiles/index'

  get 'profile/index'

 devise_for :user

 devise_for :restuarant

root to:"restuarants#show"

resources :restuarants do
  collection do
  end  
  member do 
      get 'staff'
      get 'add_drinking'
      get 'add_dessert'
      get 'add_dish'
      post 'add_staff'
      get 'show_staff'
      delete 'destroy_staff'
      get 'report'
    end
end

resources :billings   do
  member do
    get 'index_show'
    get 'report'
  end  
end

resources :registers

resources :waiters

resources :drinkings do
  member do
    patch 'update_drinking' 
  end
  collection do
    get  'drink_search'
  end
end

resources :desserts do
  member do
    patch 'update_dessert'
  end
  collection do
    get  'dessert_search'
  end
end

resources :dishs do
 member do
patch 'update_dish'
  end
  collection do
    get  'dish_search'
  end
end

resources :promotions do
  member do
  patch 'update_promotion'
  end
end

resources :bookings do
  member do
    patch 'update_booking'
  end
end

resource :users, only: [:edit, :update, :new]
  
 resources :tables
 resources :menu_lists do
  collection do
    get 'drinking'
    get 'dessert'
    get 'show'
   end
  member do
    patch 'create_menu'
    get 'payment'
    get 'service_bill'
    get "clear_table"
    get "cancle"
  end
end
  
 resources :showusers do 
 collection do
        get 'showusers'
    end
  end

  resources :profiles do 
 collection do
        get 'profiles'
    end
  end

   resources :orders do 
 collection do
        get 'orders'
    end
  end

  resources :kitchens do
    collection do
      get 'dish_kitchen'
      get 'drinking_kitchen'
      get 'dessert_kitchen'
    end
  end

end

app/models/restuarant.rb
class Restuarant
  include Mongoid::Document

   has_many :billings
   has_many :report
   has_many :memberships
   has_many :printers
   belongs_to :user
   belongs_to :waiter
   belongs_to :cashier
   has_many :drinkings
   has_many :desserts
   has_many :dishs
   has_many :tables
   has_many :promotions
   has_many :bookings
   has_many :kitchens
   has_many :menu_lists
   
   field :restuarant_name,    type: String      
   field :user_id,            type: String
   field :restuarant_owner,   type: String
   field :printer_ip,         type: String
   field :printer_name,       type: String
   field :billing_id, 		    type: Integer
   field :restuarant_address, type: String      
   field :restuarant_tel,     type: String     
   field :restuarant_email,   type: String     
   field :legal_person,       type: String            
   field :tax_id,             type: String
   field :province,           type: String
   field :county,             type: String
   field :district,           type: String
   field :branch_id,          type: Integer   


     validates :restuarant_name,                  presence: {message: "กรุณาระบุชื่อร้าน"},uniqueness: {message: "ชื่อร้านนี้ มีอยู่ในระบบแล้ว"}
     validates :restuarant_address,               presence: {message: "กรุณาระบุที่อยู่ร้าน"}
     validates :restuarant_tel,                   presence: {message: "กรุณาระบุเบอร์โทรศัพท์ของร้าน"}, numericality: {message: "เบอร์โทรศัพท์กรอกได้เฉพาะตัวเลข"}                   
     validates :legal_person,                     presence: {message: "กรุณาระบุชื่อนิติบุคคล"}    
     validates :tax_id,                           presence: {message: "กรุณาระบุเลขที่เสียภาษี"}, numericality: {message: "เลขที่เสียภาษีกรอกได้เฉพาะตัวเลข"}                    
   

               
 




def create_owner(user,restuarant)
   @owner = Membership.new(user_id: user, restuarant_id: restuarant,owner: true)
   @owner.save
end


def create_staff(user,restuarant)
   @owner = Membership.new(user_id: user, restuarant_id: restuarant)
   @owner.save
end




end

app/controllers/restuarants_controller.rb
class RestuarantsController < ApplicationController

  def new
    @restuarant= Restuarant.new
  end

  def show
    @restuarant_show = Restuarant.find(params[:id])
    @user = User.where(_id: current_user.id) 
    @user.update(current_restuarant: @restuarant_show.id) 
    @restuarant_user = Restuarant.where(user_id: current_user.id)  
    @restuarants = Restuarant.where(user_id: current_user.id)
    @table = Table.new
    @table_show = Table.where(restuarant_id: @restuarant_show.id).order(table_number: "aesc")
  end

  def staff
    @restuarant= Restuarant.find(params[:id])
    @users = User.where(restuarant_id: @restuarant.id)
    @restuarant_user = Restuarant.where(user_id: current_user.id).all 
  end

  def edit
  end

  def index
    @restuarant= Restuarant.new
    @user = User.where(_id: current_user.id) 
    @user.update(current_restuarant: nil)  
    @restuarants= Restuarant.where(user_id: current_user.id).all
  end

def create
    @restuarant = Restuarant.new(restuarant_params)
    if @restuarant.save
      @promotion = Promotion.new(promotion_name: "ไม่มีส่วนลด",promotion_discount: 0,restuarant_id: @restuarant.id)
      @promotion.save
      @restuarant.create_owner(current_user.id,@restuarant.id)
      flash[:notice] = "สร้างร้านใหม่เรียบร้อยแล้ว"
      redirect_to restuarants_path
    else
      flash[:error] = "กรุณาระบุข้อมูลให้ครบถ้วน"
      redirect_to new_restuarant_path
    end
  end

def destroy
  @des= Restuarant.find(params[:id])
  @des.destroy
  flash[:notice] = "ลบเรียบร้อยแล้ว"
  redirect_to restuarants_path
end

def add_staff
    @restuarant = Restuarant.where(id: current_user.current_restuarant)
    @restuarant = @restuarant[0]
    @user = User.new(email: params[:email],name: "N/A",surname: "N/A",tel: "N/A",
      password: "", password_confirmation:"")
    random_password = Devise.friendly_token

    @user.password = random_password
    @user.password_confirmation = random_password

    if @user.save
      @user.send_reset_password_instructions
      @restuarant.create_staff(@user.id,@restuarant.id)
      flash[:notice] = "สร้างยูสเซอร์สำเร็จแล้ว"
      redirect_to show_staff_restuarant_path(@restuarant.id)
    else
      flash.now[:error] ||= []
      flash[:error] = "กรุณาระบุข้อมูลให้ครบถ้วน"
      flash[:error] << @user.errors.full_messages.uniq.join(', ')
      redirect_to show_staff_restuarant_path(@restuarant.id)
    end
end

  def show_staff
     @membership= Membership.where(restuarant_id: current_user.current_restuarant)
     @restuarant_user = Restuarant.where(user_id: current_user.id) 
     @restuarant_show = Restuarant.where(id: current_user.current_restuarant)
     @restuarant_show = @restuarant_show[0]
  end  

  def destroy_staff
      @membership = Membership.find(params[:id])
      @user = User.where(id: @membership.user_id)
      @user.destroy
      @membership.destroy
      flash[:notice] = "ลบเรียบร้อยแล้ว"
      redirect_to show_staff_restuarant_path
  end

    
  def add_drinking
    @drinking= Restuarant.find(params[:id])
    
  end

  def add_dessert
    @dessert = Restuarant.find(params[:id])
  end

  def add_dish
    @dish = Restuarant.find(params[:id])
  end


  def restuarant_params
    params.require(:restuarant).permit(:restuarant_name , :user_id , :legal_person , :restuarant_tel , :tax_id , :restuarant_address, :restuarant_owner,
      :province,:county,:district,:branch_id)
  end

  
  def drinking_params
    params.require(:drinking).permit(:drinking_name, :restuarant_id)
  end

  def dessert_params
    params.require(:dessert).permit(:dessert_name, :restuarant_id)
  end

  def dish_params
    params.require(:dish).permit(:dish_name, :restuarant_id)
  end

end

app/helpers/restuarants_helper.rb
module RestuarantsHelper
end

app/views/restuarants/add_dessert.html.erb
<%= form_for(@dessert, url: dessert_url, method: :patch) do |f| %>
<hr>
    <div class="panel panel-primary bigmshoadow" >
      <div class="panel-heading gradient"><h3><i class="fa fa-birthday-cake"></i> เพิ่มเมนูของหวาน</h3>  
      </div>
        <div class="panel-body ">
         <div class="form-horizontal">
      
           <div class="form-group">
            <%= f.label "ชื่อเมนู: ", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "dessert_name">
        </div>
      </div>

       <div class="form-group">
            <%= f.label "ราคา", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "dessert_price">
        </div>
      </div>

           <div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<%= f.submit "ยืนยัน",class: "btn btn-success" %>
              	</div>
          </div>  
    	</div> 
  	</div>

<% end %>

app/views/restuarants/add_dish.html.erb
<%= form_for(@dish, url: dish_url, method: :patch) do |f| %>
<hr>
    <div class="panel panel-primary bigmshoadow" >
      <div class="panel-heading gradient"><h3><i class="fa fa-cutlery"></i>  เพิ่มเมนูอาหารคาว</h3>  
      </div>
        <div class="panel-body ">
         <div class="form-horizontal">
      
           <div class="form-group">
            <%= f.label "ชื่อเมนู: ", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "dish_name">
        </div>
      </div>

       <div class="form-group">
            <%= f.label "ราคา", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "dish_price">
        </div>
      </div>

           <div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<%= f.submit "ยืนยัน",class: "btn btn-success" %>
              	</div>
          </div>  
    	</div> 
  	</div>

<% end %>

app/views/restuarants/add_drinking.html.erb
<%= form_for(@drinking, url: drinking_url, method: :patch) do |f| %>
<hr>
    <div class="panel panel-primary bigmshoadow" >
      <div class="panel-heading gradient"><h3><i class="fa fa-user-plus"></i>เพิ่มเมนูเครื่องดื่ม</h3>  
      </div>
        <div class="panel-body ">
         <div class="form-horizontal">
      
           <div class="form-group">
            <%= f.label "ชื่อเมนู: ", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "drinking_name">
        </div>
      </div>

       <div class="form-group">
            <%= f.label "ราคา", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <input type="text" name= "drinking_price">
        </div>
      </div>

           <div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<%= f.submit "ยืนยัน",class: "btn btn-success" %>
              	</div>
          </div>  
    	</div> 
  	</div>

<% end %>

app/views/restuarants/add_menu.html.erb
<%= form_for(@drinking, url: drinking_url, method: :patch) do |f| %>
<hr>
    <div class="panel panel-primary bigmshoadow" >
      <div class="panel-heading gradient"><h3><i class="fa fa-user-plus"></i>เพิ่มเมนู</h3>  
      </div>
        <div class="panel-body ">
         <div class="form-horizontal">
      
           <div class="form-group">
            <%= f.label "ชื่อเมนู: ", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <%= text_field "drinking_name", '', class: "form-control" %>
        </div>
      </div>

       <div class="form-group">
            <%= f.label "ราคา: ", class: "col-sm-2 control-label"%>
          <div class="col-sm-4">
          <%= text_field "drinking_price", '', class: "form-control" %>
        </div>
      </div>

           <div class="form-group">
            	<div class="col-sm-offset-2 col-sm-10">
                	<%= f.submit "ยืนยัน",class: "btn btn-success" %>
              	</div>
          </div>  
    	</div> 
  	</div>

<% end %>

app/views/restuarants/add_staff.html.erb
<%= form_for(@user, url: registers_url,method: :post) do |f| %>
add_staff

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  เพิ่มพนักงาน
</button>

<!-- Modal -->
<form>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">ระบุอีเมลพนักงาน</h4>
      </div>
      <div class="modal-body">
  <div class="form-group">
    <label for="exampleInputEmail1">อีเมล :</label>
    <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Enter email">
  </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "สร้างบัญชีพนักงาน",class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>
</form>
<%end%>

app/views/restuarants/edit.html.erb
เช็คบิล

app/views/restuarants/index.html.erb
<hr>
    <div class="panel panel-primary" > 
        <div class="panel-heading gradient">
            <div class="col-md-5">
            <h3 style=" margin-top: 2%;"><i class="fa fa-home">&nbsp;</i> 
            ร้านของคุณ
            </h3>
       </div>
             <div class="text-right">
              <%= link_to new_restuarant_path, class: "btn btn-primary" do %> <i class="fa fa-search-plus"></i> เปิดร้านใหม่
              <%end%>
            </div>
        </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      </div>
        <div class="panel-body">
            <table class="table table-striped table-hover table-condensed">
                  <% @restuarants.each_with_index do |a, i| %>
                        <div class="col-sm-3 text-center">
                          ร้าน <%= a.restuarant_name %>
                          <p>
                          </p>
                          <%=link_to( image_tag("homepage.jpg",width:'160' ,height:'160'), restuarant_path(a)) %>
                          <p>
                          </p>
                          <%= link_to restuarant_path(a), method: :delete, data: { confirm: 'คุณต้องการจะลบร้านค้า ?' }, 
                          class: 'btn btn-danger' do %><i class="fa fa-trash-o" ></i> ลบร้านค้า
                          <%end%>
                              <hr>                  
                        </div>  
                        <%end%>
            </table>
         </div>
        </div>
        </div>

app/views/restuarants/new.html.erb
<%= form_for(@restuarant, url: restuarants_path) do |f| %>

   
<div class="panel panel-primary" >
        <div class="panel-heading gradient"><h3><i class="glyphicon glyphicon-home"></i> แบบฟอร์มสร้างร้านใหม่ </h3>  
      </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      
            <div class="form-group">
                <%= f.label :restuarant_name,"ชื่อร้าน:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_field :restuarant_name, class: "form-control"%>
                  <%= f.hidden_field :user_id, :value => current_user.id %>
                  <%= f.hidden_field :restuarant_owner, :value => current_user.name %>
                </div>
              </div>

             <div class="form-group">
                <%= f.label :legal_person ,"ชื่อนิติบุคคล:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_field :legal_person, :value => (current_user.name + " " + current_user.surname)  ,class: "form-control"%>
                 </div>
            </div>

              <div class="form-group">
                <%= f.label :restuarant_tel ,"เบอร์โทรศัพท์:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_field :restuarant_tel,  class: "form-control"%>
                </div>
              </div>

                <div class="form-group">
                <%= f.label :tax_id ,"เลขประจำตัวผู้เสียภาษี:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_field :tax_id,  class: "form-control"%>
                </div>
              </div>

               <div class="form-group">
                <%= f.label :branch_id,"รหัสสาขา:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_field :branch_id,  class: "form-control"%>
                </div>
              </div>

                <div class="form-group">
                <%= f.label :restuarant_address ,"ที่อยู่ร้าน:",class: "col-sm-2 control-label"%>
                <div class="col-sm-4">
                  <%= f.text_area  :restuarant_address,  class: "form-control"%>
                </div>
              </div>


            <div ng-controller = "ProvinceController">
              <div class="form-group">  
                <label class="col-sm-2 control-label">จังหวัด : </label>
                  <div class="col-sm-5" >
                   <ui-select ng-model="province.selected" theme="select2" ng-disabled="" style="min-width: 300px;"  on-select="selecte_province($item)">
                    <ui-select-match placeholder="ระบุจังหวัด...">{{$select.selected.province_name|| "ระบุจังหวัด..." }}</ui-select-match>
                      <ui-select-choices repeat="province in provinces | propsFilter: {province_name: $select.search}">
                        <div  ng-bind-html="province.province_name "></div>
                      </ui-select-choices>
                    </ui-select>
                  </div>
              </div>

              <input type="hidden"  name="restuarant[province]" ng-model="province.selected.province_name" ng-value="province.selected.province_name" />

              <div class="form-group">  
                <label class="col-sm-2 control-label">เขต/อำเภอ : </label>
                  <div class="col-sm-5">
                   <ui-select ng-model="county.selected" theme="select2" ng-disabled="" style="min-width: 300px;"  on-select="selecte_county($item)">
                    <ui-select-match placeholder="ระบุเขต/อำเภอ...">{{$select.selected.county_name }}</ui-select-match>
                      <ui-select-choices repeat="county in counties | propsFilter: {county_name: $select.search}">
                        <div ng-bind-html="county.county_name "></div>
                      </ui-select-choices>
                    </ui-select>
                  </div>
              </div>

              <input type="hidden"  name="restuarant[county]" ng-model="county.selected.county_name" ng-value="county.selected.county_name" />

              <div class="form-group">  
                <label class="col-sm-2 control-label">แขวง/ตำบล : </label>
                  <div class="col-sm-5">
                   <ui-select ng-model="district.selected" theme="select2" ng-disabled="" style="min-width: 300px;">
                    <ui-select-match placeholder="ระบุแขวง/ตำบล...">{{$select.selected.district_name}}</ui-select-match>
                      <ui-select-choices repeat="district in districts | propsFilter: {district_name: $select.search}">
                        <div ng-bind-html="district.district_name "></div>
                      </ui-select-choices>
                    </ui-select>
                  </div>
              </div>

              <input type="hidden"  name="restuarant[district]" ng-model="district.selected.district_name" ng-value="district.selected.district_name" />

            </div>
         
               
                  <div class="col-sm-6">
                  <p class="text-center">
                      <%= submit_tag "ตกลง", class: "btn btn-success" %>
                      <%= link_to "กลับ", restuarants_path, class: "btn btn-danger" %>
                  </p>
                  </div>
          </div>  
        </div>    
   </div>
            
   <%end%>
   

app/views/restuarants/report.html.erb
<hr>
    <div class="panel panel-primary bigmshoadow" >
        <div class="panel-heading gradient"><h3><i class="fa fa-calendar"></i> เรียกดูรายงาน</h3>  
      </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      </div>
        <div class="panel-body">
      <table class="table table-striped table-hover table-condensed">
          <thead>
            <tr>
              
              <th>วันที่เริ่ม</th>
              <th>วันที่สิ้นสุด</th>
              <th>เรียกดู</th>
                       
            </tr>
          </thead>

          <tbody>
           

              </tr>
        </tbody>
      </table>
  </div>
      </div>
      </div>

app/views/restuarants/show.html.erb
<%= form_for(@table, url: tables_url, method: :post) do |f| %>    
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        เพิ่มโต๊ะ
      </div>
      <div class="modal-body">
          <div class="form-horizontal">
      
            <div class="form-group">
              <label>จำนวนโต๊ะที่ต้องการ</label>
                <div class="col-sm-4">
                  <input type = "number" name="table" min="1" max="100" class="form-control" value="1">  </div>
            </div>
 
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="actions">
                  <%= f.submit("ยืนยัน", class: "btn btn-success") %>
                   <button type="button" class="btn btn-danger" data-dismiss="modal"> ปิด </button>
                </div>
              </div>
            </div>

          </div>       
      </div>

  </div>
</div>    
</div> 
<%end%>
<div class="row">
  <div  class="col-sm-4 text-left">
           <h3>ร้าน : <%= @restuarant_show.restuarant_name %></h3>
  </div>     
  <div class="col-sm-8 text-right">
          <h4><%= Time.now %></h4>
          <h4>พนักงาน :<%=current_user.name%> <%=current_user.surname%></h4>
  </div>
</div>
<hr>
    <% @table_show.each_with_index do |a, i| %>
      <div class="col-sm-3 text-center">
        <div>
        <button class="btn btn-info" type="button">
           โต๊ะที่ <span class="badge"><%= a.table_number %></span>
        </button>
        </div>
        <p>
        </p>  
        <%=link_to( image_tag("table1.png",width:'140' ,height:'120'), menu_list_path(a)) %><br>
        <p>
        </p>
        <% if current_user.super_user? %>
         <%= link_to table_path(a), method: :delete, data: { confirm: 'ยืนยันการลบ' }, 
                class: 'btn btn-danger' do %><i class="fa fa-trash-o" ></i> ลบ
                    <%end%>
        <%end%>
       
        <hr>                  
      </div>  
    <%end%> 

app/views/restuarants/show_staff.html.erb
<hr>
    <div class="panel panel-primary bigmshoadow" > 
        <div class="panel-heading gradient">
       		<div class="col-md-6">
			<h3 style=" margin-top: 2%;"><i class="fa fa-users">&nbsp;</i> 
      		พนักงานทั้งหมด
        	</h3>
       </div>
             <div class="text-right">
             	<button  type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"> <i class="fa fa-user-plus"></i> เพิ่มพนักงาน</button>
            </div>
        </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      </div>
        <div class="panel-body">
			<table class="table table-striped table-hover table-condensed">
			    <thead>
			      <tr class="info">
			        <th>ชื่อ</th>
			        <th>นามสกุล</th>
			        <th>อีเมล</th>
			        <th>เบอร์โทรศัพท์</th>
			        <th>สถานะ</th>	
			        <th></th>	     
			      </tr>
			    </thead>
			    <tbody>
			      <% @membership.each_with_index do |f| %>
				      <tr>
				        <%if f.user.super_user? %>	 		 
			              		
						        <td><%= f.user.name %></td>
						        <td><%= f.user.surname %></td>
						        <td><%= f.user.email %></td>
						        <td><%= f.user.tel %></td>
						        <td><font color = red> เจ้าของร้าน </font></td>
						        <td></td>

					        <% else%>
						        
						        <td><%=  f.user.name %></td>
						        <td><%=  f.user.surname %></td>
						        <td><%=  f.user.email %></td>
						        <td><%=  f.user.tel %></td>
						        <td><font color = green> พนักงาน </font></td>
						        <td class="text-right"><%= link_to destroy_staff_restuarant_path(f), method: :delete, data: { confirm: 'ยืนยันการลบ' }, 
                					class: 'btn btn-danger' do %><i class="fa fa-trash-o" ></i>
                					<%end%>
                				</td>
		
			          <%end%>
				      </tr>
				   <%end%>
			  </tbody>
			</table>
		</div>
	</div>

 <%= form_for(@restuarant_show, url: add_staff_restuarant_url,method: :post) do |f| %>	

  		<!-- Modal -->
<form>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">เพิ่มพนักงาน</h4>
      </div>
      <div class="modal-body">
  <div class="form-group">
    <label for="exampleInputEmail1">อีเมล :</label>
    <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="Enter email">
  </div>
      </div>
      <div class="modal-footer">
        <%= f.submit "สร้างบัญชีพนักงาน",class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>
</div>
</form>
<%end%>

app/views/restuarants/staff.html.erb
<h2>แสดงรายชื่อพนักงาน</h2><hr>
    <div class="panel panel-primary bigmshoadow" >
        <div class="panel-heading gradient"><h3><i class="glyphicon glyphicon-file"></i> แสดงรายชื่อพนักงาน</h3>  
      </div>
        <div class="panel-body ">
          <div class="form-horizontal">
      </div>
        <div class="panel-body">
			<table class="table table-striped table-hover table-condensed">
			    <thead>
			      <tr>
			        
			        <th>ชื่อ</th>
			        <th>นามสกุล</th>
			        <th>อีเมลล์</th>
			        <th>เบอร์โทรศัพ</th>
		        			     
			      </tr>
			    </thead>

			    <tbody>
			      <% @users.each_with_index do |f| %>
				      <tr>
				        <%if f.super_user %>	 		 
			              		
						        <td><%= f.name %></td>
						        <td><%= f.surname %></td>
						        <td><%= f.email %></td>
						        <td><%= f.tel %></td>
						      
						        <td><center><font color =red> เจ้าของร้าน </font></center></td>
						        <td></td>

					        <% else%>
						        
						        <td><%= f.name %></td>
						        <td><%= f.surname %></td>
						        <td><%= f.email %></td>
						        <td><%= f.tel %></td>
						        <td><%= link_to 'Delete', showuser_path(f), method: :delete, data: { confirm: 'Are you sure?' } %><td>
						        <td><center><font color =green> พนักงาน </font></center></td>
						        
					       

					        
			          <%end%>

				      </tr>
				   <%end%>
			  </tbody>
			</table>
  </div>
     	</div>
     	</div>