config/routes.rb
Rails.application.routes.draw do

  get 'welcomes/index'

  get 'profiles/index'

  get 'profile/index'

 devise_for :user

 devise_for :restuarant

root to:"restuarants#show"

resources :restuarants do
  collection do
  end  
  member do 
      get 'staff'
      get 'add_drinking'
      get 'add_dessert'
      get 'add_dish'
      post 'add_staff'
      get 'show_staff'
      delete 'destroy_staff'
      get 'report'
    end
end

resources :billings   do
  member do
    get 'index_show'
    get 'report'
  end  
end

resources :registers

resources :waiters

resources :drinkings do
  member do
    patch 'update_drinking' 
  end
  collection do
    get  'drink_search'
  end
end

resources :desserts do
  member do
    patch 'update_dessert'
  end
  collection do
    get  'dessert_search'
  end
end

resources :dishs do
 member do
patch 'update_dish'
  end
  collection do
    get  'dish_search'
  end
end

resources :promotions do
  member do
  patch 'update_promotion'
  end
end

resources :bookings do
  member do
    patch 'update_booking'
  end
end

resource :users, only: [:edit, :update, :new]
  
 resources :tables
 resources :menu_lists do
  collection do
    get 'drinking'
    get 'dessert'
    get 'show'
   end
  member do
    patch 'create_menu'
    get 'payment'
    get 'service_bill'
    get "clear_table"
    get "cancle"
  end
end
  
 resources :showusers do 
 collection do
        get 'showusers'
    end
  end

  resources :profiles do 
 collection do
        get 'profiles'
    end
  end

   resources :orders do 
 collection do
        get 'orders'
    end
  end

  resources :kitchens do
    collection do
      get 'dish_kitchen'
      get 'drinking_kitchen'
      get 'dessert_kitchen'
    end
  end

end

app/models/billing.rb
class Billing
  include Mongoid::Document

  belongs_to :user
  belongs_to :table
  belongs_to :restuarant
  has_many :menu_lists
  belongs_to :promotion

  field :billing_number,        type: String
  field :time,                  type: Time
  field :date,					type: Date

end
 	

app/controllers/billings_controller.rb
class BillingsController < ApplicationController

	def index_show
		@restuarant_show = Restuarant.where(id: current_user.current_restuarant).first
    	@restuarant_user = Restuarant.where(user_id: current_user.id) 
    	@restuarant= Restuarant.where(id: current_user.current_restuarant).first
    	@report = MenuList.where(restuarant_id: current_user.current_restuarant)
		date_start = params[:date_start]
		date_end = params[:date_end]
		if date_start != nil && date_end != nil
			@billing = Billing.where(:date.gte => date_start, :date.lte => date_end)
		else
			@billing = Billing.where(restuarant_id: current_user.current_restuarant)
		end
   
		  respond_to do |format|
		  	format.html
		  	format.csv { send_data @report.to_csv, filename: "Report-#{Date.today}.csv"}
		  end
	end


	def show
		@billing = Billing.find(params[:id])
		@show_menu = MenuList.where(billing_id: @billing.id, cancle: false)
		@total = @show_menu.map { |i| i.menu_price.to_f * i.value.to_f}.compact.sum
		@promotion = (@total.to_f * @promotion_discount.to_f)/100
	end

	def report
		@restuarant_show = Restuarant.where(id: current_user.current_restuarant).first
    	@restuarant_user = Restuarant.where(user_id: current_user.id) 
    	@restuarant = Restuarant.where(id: current_user.current_restuarant).first
		@report = MenuList.where(restuarant_id: current_user.current_restuarant)
	end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/index.html.erb
<%= form_tag(billings_path,method: :get) do |f| %>
<input type="hidden"  name="check" value="1">
  <div class="form-group"> 
    <%= label_tag "Date","วันที่ :", class: "col-sm-2 control-label" %>
      <div class="col-sm-3">
       <%= text_field_tag 'date_start',Date.today.strftime("%Y-%m-%d"),readonly: true, id: 'today_date_picked',class: "form-control"%>
      </div>
      <div class="col-sm-0.1"> 
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
      </div> 
  </div>

    <div class="form-group"> 
    <%= label_tag "Date","วันที่ :", class: "col-sm-2 control-label" %>
      <div class="col-sm-3">
       <%= text_field_tag 'date_end',Date.today.strftime("%Y-%m-%d"),readonly: true, id: 'today_date_picked2',class: "form-control"%>
      </div>
      <div class="col-sm-0.1"> 
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked2" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
      </div> 
  </div>

  <button class="btn btn-success" type="submit" ><i class="fa fa-search"></i> ค้นหา</button>
<%end%>
<hr>

    <div class="panel panel-primary">
      <div class="panel-heading"><h4>รายงานการขาย<h4></div>
        <div class="panel-body">
          <table class="table table-striped" id="show_data1">
            <thead>
            <tr>
              <th>#</th>
              <th>billing_number</th>
              <th>วันที</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
              <% @billing.each_with_index do |a, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <td><%=a.billing_number%></td>
                <td><%=a.date%></td>
                <td><%= link_to "see", billing_path(a)%>
              </tr>
              </div>
              <%end%>
              </tbody>
          </table>
        </div>
      </div>

app/views/billings/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Sheet1">
<Table>
	<Row>
		<Cell><Data ss:Type="String">ID</Data></Cell>
		<Cell><Data ss:Type="String">Name</Data></Cell>
		<Cell><Data ss:Type="String">Release Date</Data></Cell>
		<Cell><Data ss:Type="String">Price</Data></Cell>
	</Row>
	<% @products.each do |product| %>
	<Row>
		<Cell><Data ss:Type="Number"><%= product.id %> </Data></Cell>
		<Cell><Data ss:Type="String"><%= product.name %> </Data></Cell>
		<Cell><Data ss:Type="String"><%= product.released_on %> </Data></Cell>
		<Cell><Data ss:Type="Number"><%= product.price %> </Data></Cell>
	</Row>
	<% end %>
</Table>
</Worksheet>
</Workbook>

app/views/billings/index_show.html.erb
<%= form_tag(index_show_billing_path,method: :get) do |f| %>
<input type="hidden"  name="check" value="1">

  <div class="form-group"> 
    <%= label_tag "Date","วันที่เริ่มต้น :", class: "col-sm-2 control-label" %>
      <div class="col-sm-3">
       <%= text_field_tag 'date_start',Date.today.strftime("%Y-%m-%d"),readonly: true, id: 'today_date_picked',class: "form-control"%>
      </div>
      <div class="col-sm-0.1"> 
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
      </div> 
  </div>

    <div class="form-group"> 
    <%= label_tag "Date","วันที่สิ้นสุด :", class: "col-sm-2 control-label" %>
      <div class="col-sm-3">
       <%= text_field_tag 'date_end',Date.today.strftime("%Y-%m-%d"),readonly: true, id: 'today_date_picked2',class: "form-control"%>
      </div>
      <div class="col-sm-0.1"> 
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked2" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
      </div> 
  </div>
<div>
  <button class="btn btn-primary" type="submit" ><i class="fa fa-search"></i> ค้นหา</button> <%end%> 
  <%= link_to index_show_billing_path(format: "csv"), class: 'btn btn-success'  do %><i class="fa fa-file-text" ></i> Export
  <%end%>
</div>

<hr>
    <div class="panel panel-primary">
      <div class="panel-heading"><h4><i class="fa fa-pencil-square-o"></i> รายงานการขาย<h4></div>
        <div class="panel-body">
          <table class="table table-striped" id="show_data1">
            <thead>
            <tr class="info">
              <th>#</th>
              <th>หมายเลขบิล</th>
              <th>วันที</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
              <% @billing.each_with_index do |a, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <td><%=a.billing_number%></td>
                <td><%=a.date%></td>
                <td><%= link_to "ดู", billing_path(a)%>
              </tr>
              </div>
              <%end%>
              </tbody>
          </table>
        </div>
      </div>

app/views/billings/report.html.erb
    <div class="panel panel-primary">
      <div class="panel-heading"><h4>รายงานการขาย<h4></div>
        <div class="panel-body">
          <table class="table table-striped" id="show_datal">
            <thead>
            <tr class="info">
              <th>billing_number</th>
              <th>วันที่</th>
              <th>พนักงาน</th>
              <th>ชื่ออาหาร</th>
              <th>จำนวน</th>
              <th>ราคา/บาท</th>
              <th>เป็นเงิน(บาท)</th>
              <th>รวม</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
              <% @report.each_with_index do |a, i| %>
              <tr>
                <td><%=a.billing.billing_number %></td>
                <td><%=a.billing.date%></td>
                <td><%=a.billing.user.name%></td>
                <td><%=a.menu%></td>
                <td><%=a.value%></td>
                <td><%=a.menu_price.to_f %></td>
                <td><%=a.menu_price.to_f * a.value %></td>
                <td></td>
                <%= p%>
              </tr> 
              <%end%>
              
              </div>  
              </tbody>
          </table>
        </div>
      </div>
    </div>


    <<!-- input type="hidden"  name="check" value="1">
<div class="row">
<div class="col-sm-6">
<form class="form-horizontal">
<div class="form-gruop">
  <label for="inputEmail3" class="col-sm-2 control-label">เริ่มต้น :</label>
    <div class="col-sm-8">
      <input type="email" class="form-control" id="inputEmail3">
    </div>
    <div class="col-sm-0.1">
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
    </div>
</div>
<div class="form-gruop" style="padding-top:2%">
  <label for="inputEmail3" class="col-sm-2 control-label">สิ้นสุด :</label>
    <div class="col-sm-8">
      <input type="email" class="form-control" id="inputEmail3">
    </div>
    <div class="col-sm-0.1">
        <button type="button" class="btn btn-warning show-datepicker" data-target="#today_date_picked" class= "form-control">
        <span class="fa fa-calendar"></span>
        </button>
    </div>
</div>
</form>
</div>
<div class="col-sm-2 col-sm-offset-3" >
        <%=link_to( image_tag("export_excel 1.jpg",width:'120' ,height:'120'), index_show_billing_path(format: "csv")) %>
</div>
</div> -->

app/views/billings/show.html.erb
<center><h4>สรุปยอดสั่งอาหารและเครื่องดื่ม</h4></center>
<hr>
<div>
  ร้าน : <%= @billing.table.restuarant.restuarant_name %> <br>
  โต๊ะ : <%= @billing.table.table_number %>  <br>                                             
  ชื่อพนักงาน :  <%= @billing.user.name%> <%= @billing.user.surname%> <br>
  วันที่/เวลา : <%= @billing.time %>
</div>
<hr>
    <div class="panel panel-default">
      <div class="panel-heading"><h4>รายการอาหาร<h4></div>
        <div class="panel-body">
          <table class="table table-striped" id="show_datal">
            <thead>
            <tr>
              <th>#</th>
              <th>ชื่ออาหาร</th>
              <th>จำนวน</th>
              <th>ราคา/บาท</th>
              <th>เป็นเงิน(บาท)</th>
            </tr>
          </thead>
          <tbody>
              <% @show_menu.each_with_index do |a, i| %>
              <tr>
                <td><%= i + 1 %></td>
                <td><%=a.menu%></td>
                <td><%=a.value%></td>
                <td><%=a.menu_price.to_f %></td>
                <td><%=a.menu_price.to_f * a.value %></td>
              </tr> 
              <%end%>
              
              </div>  
              </tbody>
          </table>
          <div class = "col-sm-6 col-sm-offset-8">
              รวม <%= @total %> บาท
          </div>
          <div class = "col-sm-6 col-sm-offset-8">
          <% if @promotion_discount.to_i == 100 %>
            ส่วนลด  0%     บาท
          <% else %>  
            ส่วนลด <%= @promotion_discount %> % 
          <%end%>  
          </div>
          <br>
          <div class = "col-sm-6 col-sm-offset-8">
          <% if @promotion_discount.to_i == 100 %>
           รวมสุทธิ <%= @total%>   บาท
          <% else %>  
            รวมสุทธิ <%= @total - @promotion %>  บาท
          <%end%>  
          </div>
        </div>
 <hr>

    